services:
  mock-bank-service:
    image: ghcr.io/onyxpayments/mock-bank-service:latest
    ports:
      - "8001:8000"

  payment-orchestrator-service:
    image: ghcr.io/onyxpayments/payment-orchestrator-service:latest
    ports:
      - "8002:8001"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BANK_SERVICE_URL: ${BANK_SERVICE_URL}
    depends_on:
      - mock-bank-service
      - orchestrator-db

  orchestrator-db:
    image: postgres:17
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - transactions_data:/var/lib/postgresql/data
      - ./postgres/transactions/init:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  transactions_data:
  webhooks_data: