services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres-transactions:
    image: postgres:17
    environment:
      POSTGRES_DB: transactions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - transactions_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  postgres-webhooks:
    image: postgres:17
    environment:
      POSTGRES_DB: webhook_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - webhooks_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  mock-bank-service:
    image: ghcr.io/rodrigueezj/mock-bank-service:latest
    ports:
      - "8001:8000"

  payment-orchestator-service:
    image: ghcr.io/rodrigueezj/payment-orchestator-service:latest
    ports:
      - "8002:8001"

volumes:
  transactions_data:
  webhooks_data: